/**
 * Category mappings for different book types
 */

export const SCHOOL_CATEGORIES = [
  "Accounting",
  "Afrikaans",
  "Agricultural Management",
  "Agricultural Sciences",
  "Ancient Languages",
  "Animal Husbandry",
  "Architecture",
  "Art & Design",
  "Arts & Humanities",
  "Astronomy",
  "Automotive",
  "Bacteriology",
  "Biology",
  "Business Management",
  "Business Studies",
  "Career Guidance",
  "Chemistry",
  "Chinese",
  "Clothing & Textiles",
  "Communication",
  "Computer Applications",
  "Computer Programming",
  "Consumer Studies",
  "Cosmetology",
  "Dance",
  "Design & Technology",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Electronic Media",
  "Electronics",
  "Engineering",
  "Engineering Graphics",
  "English",
  "English Language & Literature",
  "Environmental Management",
  "Environmental Studies",
  "Family & Consumer Sciences",
  "Fashion Design",
  "Film & Media",
  "Finance",
  "Food Technology",
  "Foreign Languages",
  "French",
  "Furniture Making",
  "Geography",
  "German",
  "Global Citizenship",
  "Government & Politics",
  "Graphic Design",
  "Greek",
  "Hair & Beauty",
  "Health & Safety",
  "Health Science",
  "Hindi",
  "History",
  "Home Economics",
  "Hospitality & Tourism",
  "Hotel Management",
  "Human Physiology",
  "Humanities",
  "ICT / IT",
  "Industrial Management",
  "Information Technology",
  "Instrumentation",
  "Interiors & Furnishings",
  "Japanese",
  "Journalism",
  "Jwagwan",
  "Labour Relations",
  "Latin",
  "Law",
  "Leadership & Management",
  "Leotho Sesotho",
  "Library & Information Science",
  "Life Orientation",
  "Life Sciences",
  "Languages",
  "Literature",
  "Logistics",
  "Maintenance & Management",
  "Management",
  "Manufacturing",
  "Marine Biology",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Mechanics",
  "Media Studies",
  "Medical Science",
  "Medicine",
  "Merchandising",
  "Metallurgy",
  "Microbiology",
  "Mining",
  "Modern European Studies",
  "Modern Greek",
  "Modern Languages",
  "Modern Zulu",
  "Molecular Biology",
  "Money Management",
  "Morphology",
  "Music",
  "Musicology",
  "Mythology",
  "National Schools Curriculum",
  "Nature Conservation",
  "Natural Sciences",
  "Navigation",
  "Ndebele",
  "Nursing",
  "Office Management",
  "Occupational Health & Safety",
  "Operations Management",
  "Optics",
  "Organisation & Management",
  "Organisational Development",
  "Oriental Languages",
  "Ornithology",
  "Pharmacology",
  "Philosophy",
  "Physical Education",
  "Physical Science",
  "Physics",
  "Physiology",
  "Plant Science",
  "Plumbing",
  "Poetry & Drama",
  "Political Science",
  "Politics",
  "Portuguese",
  "Powder Metallurgy",
  "Psychology",
  "Public Administration",
  "Public Health",
  "Public Speaking",
  "Publishing",
  "Quality Assurance",
  "Quantitative Methods",
  "Quantity Surveying",
  "Radiotherapy",
  "Radio & Television",
  "Railway Studies",
  "Real Estate",
  "Recreation & Leisure",
  "Religious Studies",
  "Religious Education",
  "Research Methodology",
  "Respiratory Therapy",
  "Retailing",
  "Rock Climbing",
  "Russian",
  "Safety & Health",
  "Sales Management",
  "Sandhi",
  "Sanskrit",
  "Science",
  "Science & Technology",
  "Sea Studies",
  "Secretarial Studies",
  "Securities",
  "Self-Defence",
  "Sepedi",
  "Sesotho",
  "Setswana",
  "Shebeen Studies",
  "Shipyard Studies",
  "Shiteneni Shona",
  "Shoe Making",
  "Shona",
  "Sign Language",
  "Sikhism",
  "Social Development",
  "Social Sciences",
  "Social Studies",
  "Sociology",
  "Spanish",
  "Special Education",
  "Speech & Language Pathology",
  "Sport & Recreation",
  "Sport Management",
  "Sports Science",
  "Staining & Polishing",
  "Standard Grade Studies",
  "Statistics",
  "Stenography",
  "Store Management",
  "Strategic Management",
  "Strategies for Learning",
  "Structural Design",
  "Studies in Religion",
  "Study Skills",
  "Sudanese",
  "Sugarcane Production",
  "Supply Chain Management",
  "Sustainable Development",
  "Swahili",
  "Swedish",
  "Systems Administration",
  "Systems Analysis",
  "Taxation",
  "Teaching & Learning",
  "Technical Drawing",
  "Technical Graphics",
  "Technology",
  "Telecommunications",
  "Textile Design",
  "Textile Technology",
  "Thai",
  "Theatre",
  "Theology",
  "Theory of Knowledge",
  "Tourism",
  "Tourism Management",
  "Track Management",
  "Transport Management",
  "Travel & Tourism",
  "Trigonometry",
  "Turkish",
  "Typing & Keyboard",
  "Understanding Differences",
  "Urban & Regional Planning",
  "Urban Planning",
  "Veterinary Science",
  "Vietnamese",
  "Virology",
  "Visual Arts",
  "Viticulture",
  "Vocational & Technical Studies",
  "Waste Management",
  "Water Resources",
  "Wear & Tear",
  "Weaving",
  "Web Design & Development",
  "Wedding Planning",
  "Welding",
  "Wells & Boreholes",
  "Winemaking",
  "Wood Science",
  "Woodwork",
  "Working with Children",
  "Workplace Communication",
  "World Geography",
  "World History",
  "World Literature",
  "World Religions",
  "Writing",
  "Xerox & Offset Printing",
  "Xhosa",
  "Yoga",
  "Youth & Community Development",
  "Zoology",
  "Zulu",
];

export const UNIVERSITY_CATEGORIES = [
  "Accounting",
  "Actuarial Science",
  "Administration",
  "Advertising",
  "Aeronautical Engineering",
  "African Studies",
  "Agricultural Economics",
  "Agricultural Engineering",
  "Agricultural Sciences",
  "Agronomy",
  "Algorithms",
  "American Studies",
  "Anatomy",
  "Ancient History",
  "Ancient Languages",
  "Animal Science",
  "Anthropology",
  "Applied Linguistics",
  "Applied Mathematics",
  "Archaeology",
  "Architecture",
  "Area Studies",
  "Art",
  "Art History",
  "Arts",
  "Asian Studies",
  "Astronomy",
  "Astrophysics",
  "Atmospheric Sciences",
  "Audiology",
  "Australian Indigenous Studies",
  "Australian Studies",
  "Automotive Engineering",
  "Aviation",
  "Bacteriology",
  "Banking",
  "Behavioral Science",
  "Biochemistry",
  "Bioethics",
  "Bioinformatics",
  "Biological Engineering",
  "Biological Sciences",
  "Biology",
  "Biomedical Engineering",
  "Biomedical Science",
  "Biophysics",
  "Biotechnology",
  "Black Studies",
  "Botany",
  "Broadcast Journalism",
  "Broadcasting",
  "Building & Construction",
  "Building Technology",
  "Business",
  "Business Administration",
  "Business Analytics",
  "Business Economics",
  "Business Information Systems",
  "Business Management",
  "Business Studies",
  "Business Systems",
  "Chemical Engineering",
  "Chemistry",
  "Chinese",
  "Chinese Studies",
  "Cinema Studies",
  "Civil Engineering",
  "Classical Languages",
  "Classical Studies",
  "Clinical Psychology",
  "Commercial Law",
  "Communication",
  "Communication Studies",
  "Community Development",
  "Community Health",
  "Community Psychology",
  "Comparative Literature",
  "Computational Biology",
  "Computational Chemistry",
  "Computational Physics",
  "Computer Engineering",
  "Computer Graphics",
  "Computer Networks",
  "Computer Science",
  "Computing",
  "Conflict Resolution",
  "Conservation Biology",
  "Construction Management",
  "Consumer Psychology",
  "Contemporary History",
  "Control Systems",
  "Corporate Finance",
  "Corporate Law",
  "Corporate Social Responsibility",
  "Counseling Psychology",
  "Cosmetics",
  "Counseling",
  "Criminology",
  "Critical Care Nursing",
  "Cultural Anthropology",
  "Cultural Studies",
  "Curatorial Studies",
  "Current Events Studies",
  "Curriculum & Instruction",
  "Cybersecurity",
  "Dairy Science",
  "Dance",
  "Data Analytics",
  "Data Science",
  "Database Management",
  "Demography",
  "Dental Hygiene",
  "Dentistry",
  "Design",
  "Design Technology",
  "Development Economics",
  "Developmental Biology",
  "Developmental Psychology",
  "Dietetics",
  "Diplomacy",
  "Digital Art",
  "Digital Design",
  "Digital Media",
  "Digital Telecommunications",
  "Directed Studies",
  "Disability Studies",
  "Discrete Mathematics",
  "Disease Ecology",
  "Distributed Systems",
  "Diversity & Inclusion",
  "Drama",
  "Drama & Theatre",
  "Drawing",
  "Dyslexia Studies",
  "Earth & Planetary Sciences",
  "Earth Science",
  "Ecology",
  "Economics",
  "Education",
  "Education Policy",
  "Educational Administration",
  "Educational Leadership",
  "Educational Psychology",
  "Educational Technology",
  "Electrical Engineering",
  "Electrical Systems",
  "Electronics",
  "Elementary Education",
  "Emergency Management",
  "Emergency Medicine",
  "Emerging Markets",
  "Emerging Media",
  "Employment Relations",
  "Energy Engineering",
  "Engineering",
  "Engineering Physics",
  "English",
  "English as a Second Language",
  "English Language & Literature",
  "English Literature",
  "Entomology",
  "Environmental Analysis",
  "Environmental Chemistry",
  "Environmental Economics",
  "Environmental Engineering",
  "Environmental Ethics",
  "Environmental Health",
  "Environmental Law",
  "Environmental Management",
  "Environmental Policy",
  "Environmental Science",
  "Environmental Sciences",
  "Environmental Studies",
  "Epidemiology",
  "Epistemology",
  "Equilibrium Economics",
  "Equipment Management",
  "Ethnobiology",
  "Ethnography",
  "Ethnomusicology",
  "European History",
  "European Languages",
  "European Studies",
  "Events Management",
  "Exercise Science",
  "Existential Philosophy",
  "Experimental Physics",
  "Expert Systems",
  "Exploration & Paleontology",
  "Expository Writing",
  "Facilities Management",
  "Family Law",
  "Family Psychology",
  "Family Therapy",
  "Fashion",
  "Fashion Design",
  "Fashion Management",
  "Fashion Marketing",
  "Film & Media Studies",
  "Film & Video Production",
  "Film Production",
  "Film Studies",
  "Finance",
  "Financial Accounting",
  "Financial Economics",
  "Financial Engineering",
  "Financial Management",
  "Financial Mathematics",
  "Financial Planning",
  "Fine Art",
  "Fine Arts",
  "Fisheries Science",
  "Fitness Management",
  "Flight Operations",
  "Fluid Dynamics",
  "Food Business Management",
  "Food Chemistry",
  "Food Engineering",
  "Food Microbiology",
  "Food Science",
  "Food Science & Nutrition",
  "Food Technology",
  "Forensic Accounting",
  "Forensic Anthropology",
  "Forensic Biology",
  "Forensic Chemistry",
  "Forensic Science",
  "Forestry",
  "Forestry Science",
  "Formal Semantics",
  "French",
  "French Studies",
  "Friction",
  "Fund Management",
  "Functional Linguistics",
  "Functional Programming",
  "Game Design",
  "Game Development",
  "Gaming",
  "Gastroenterology",
  "Gender Studies",
  "Gene Therapy",
  "General Engineering",
  "General Medicine",
  "General Practice",
  "General Studies",
  "Generative Linguistics",
  "Genetic Counseling",
  "Genetic Engineering",
  "Genetics",
  "Genomics",
  "Geochemistry",
  "Geography",
  "Geoinformatics",
  "Geology",
  "Geomatics",
  "Geometry",
  "Geomorphology",
  "Geophysics",
  "Geopolitics",
  "German",
  "German Studies",
  "Gerontology",
  "Gerontological Nursing",
  "Gestalt Therapy",
  "Gestation & Birth",
  "Global Business",
  "Global Citizenship",
  "Global Economics",
  "Global Health",
  "Global History",
  "Global Politics",
  "Global Studies",
  "Global Trade",
  "Globalization Studies",
  "Government",
  "Government & Politics",
  "Graphic Communication",
  "Graphic Design",
  "Graphic Illustration",
  "Graphics & Visualization",
  "Greek",
  "Greek Civilization",
  "Greek History",
  "Green Building",
  "Green Energy",
  "Groundwater Engineering",
  "Group Psychology",
  "Growth & Development",
  "Guidance & Counseling",
  "Hair & Beauty Management",
  "Haitian Studies",
  "Hand Therapy",
  "Hardware Engineering",
  "Hawaiian Studies",
  "Health Administration",
  "Health Care Administration",
  "Health Care Law",
  "Health Economics",
  "Health Education",
  "Health Informatics",
  "Health Management",
  "Health Policy",
  "Health Psychology",
  "Health Sciences",
  "Health Service Administration",
  "Healthcare Management",
  "Hearing Science",
  "Hebrew",
  "Heritage Studies",
  "Hidden Markov Models",
  "High Energy Physics",
  "Hillel Studies",
  "Hindi",
  "Hindu Studies",
  "Hispanic Studies",
  "Historical Geography",
  "Historical Linguistics",
  "Historical Perspectives",
  "Historical Theology",
  "History",
  "History & Philosophy of Science",
  "History & Politics",
  "History of Africa",
  "History of America",
  "History of Architecture",
  "History of Art",
  "History of Asia",
  "History of the Caribbean",
  "History of Computing",
  "History of Design",
  "History of Education",
  "History of Europe",
  "History of Law",
  "History of Mathematics",
  "History of Medicine",
  "History of Middle East",
  "History of Music",
  "History of Philosophy",
  "History of Physics",
  "History of Religion",
  "History of Science",
  "History of Technology",
  "History of the Pacific",
  "Holistic Health",
  "Holistic Nursing",
  "Holy Land Studies",
  "Home Economics",
  "Home Management",
  "Homeland Security",
  "Homeopathy",
  "Horticulture",
  "Horticulture Science",
  "Hospitality",
  "Hospitality Management",
  "Hotel Administration",
  "Hotel Management",
  "Housing",
  "Housing & Community Development",
  "Human & Social Biology",
  "Human Anatomy",
  "Human Development",
  "Human Factors Engineering",
  "Human Genetics",
  "Human Geography",
  "Human Immunology",
  "Human Kinetics",
  "Human Nutrition",
  "Human Physiology",
  "Human Resource Management",
  "Human Resource Planning",
  "Human Resources",
  "Human Resources Development",
  "Human Rights",
  "Human Rights Law",
  "Humanities",
  "Humanities & Social Sciences",
  "Humanities Studies",
  "Hydrobiology",
  "Hydrology",
  "Hydropower Engineering",
  "Hygiene",
  "Hypertension",
  "Hypnotherapy",
  "Iberian Studies",
  "Ice Hotel Management",
  "Ichthyology",
  "Icon & Orthodox Studies",
  "Iconography",
  "ICT",
  "ID Systems",
  "Ideal Theory",
  "Ideal Studies",
  "Identification",
  "Identity & Belonging",
  "Identity Politics",
  "Identity Studies",
  "Ideological Studies",
  "Ideologies",
  "Idiom Studies",
  "Idiosyncratic Studies",
  "Idol Studies",
  "Idyll Studies",
  "Igneous Geology",
  "Igbo Studies",
  "Image Analysis",
  "Image Processing",
  "Imagery",
  "Imaginative Writing",
  "Imagology",
  "Imago Dei Studies",
  "Imago Psychology",
  "Imbalance Studies",
  "Imbibition",
  "Imitation Studies",
  "Immanence Studies",
  "Immateriality Studies",
  "Immigration Law",
  "Immigration Studies",
  "Immobilization Techniques",
  "Immortality Studies",
  "Immune Function",
  "Immune System Studies",
  "Immunochemistry",
  "Immunodeficiency",
  "Immunoelectrophoresis",
  "Immunogenetics",
  "Immunoglobulin Studies",
  "Immunohematology",
  "Immunoinformatics",
  "Immunology",
  "Immunopathology",
  "Immunopharmacology",
  "Immunophysiology",
  "Immunotoxicology",
  "Impact Studies",
  "Impairment Studies",
  "Impalement Studies",
  "Imparipinnate Studies",
  "Impartation Studies",
  "Impartial Observer Theory",
  "Impasse Negotiation",
  "Impassibility",
  "Impassioned Studies",
  "Impassivity Studies",
  "Impatience Studies",
  "Impeachment Law",
  "Impeachment Studies",
  "Impedance Matching",
  "Impeded Speech",
  "Impeding Factors",
  "Impellers & Pumps",
  "Impelling Force",
  "Impend Studies",
  "Impending Adjudication",
  "Impending Catastrophe",
  "Impenetrability Studies",
  "Impenetrable Studies",
  "Impenitence Studies",
  "Imperative Grammar",
  "Imperative Logic",
  "Imperative Mood",
  "Imperative Philosophy",
  "Imperative Pragmatics",
  "Imperatorships",
  "Imperceivable Studies",
  "Imperceptibility",
  "Imperceptible Studies",
  "Imperceptive Studies",
  "Imperfection Studies",
  "Imperfectionist Philosophy",
  "Imperfective Aspect",
  "Imperial Chemistry",
  "Imperial Economics",
  "Imperial Geography",
  "Imperial German",
  "Imperial History",
  "Imperial Law",
  "Imperial Politics",
  "Imperial Studies",
  "Imperialism",
  "Imperialistic Systems",
  "Imperil Studies",
  "Imperious Studies",
  "Imperish Studies",
  "Imperishability",
  "Imperishable Studies",
  "Imperium Studies",
  "Impermanence Studies",
  "Impermanent Studies",
  "Impermeable Studies",
  "Impermissible Studies",
  "Impersonal Analysis",
  "Impersonal Grammar",
  "Impersonal Lyric",
  "Impersonal Narrative",
  "Impersonal Passives",
  "Impersonal Poetry",
  "Impersonal Pronouns",
  "Impersonal Verb",
  "Impersonal Writing",
  "Impersonality Studies",
  "Impersonation Law",
  "Impersonation Psychology",
  "Impersonation Studies",
  "Impersonator Studies",
  "Impertinence Studies",
  "Impertinency",
  "Impertinent Studies",
  "Impertinently",
  "Imperturbability",
  "Imperturbable Studies",
  "Imperturbation",
  "Impervious Studies",
  "Imperviously",
  "Imperviousness",
  "Impetigo Studies",
  "Impetus Studies",
  "Impiety Studies",
  "Impinge Studies",
  "Impingement Studies",
  "Impious Studies",
  "Impiously",
  "Impious Philosophy",
  "Impishly",
  "Impishness Studies",
  "Implacability",
  "Implacable Studies",
  "Implacably",
  "Implact Studies",
  "Implanted Studies",
  "Implantation Studies",
  "Implants & Prosthetics",
  "Implastic Studies",
  "Implead Law",
  "Implement & Tool Design",
  "Implementation Studies",
  "Implementer Studies",
  "Implicate Logic",
  "Implicate Studies",
  "Implication Logic",
  "Implication Studies",
  "Implicational Studies",
  "Implicative Grammar",
  "Implicative Statements",
  "Implicative Universal",
  "Implicit Bias",
  "Implicit Cognition",
  "Implicit Learning",
  "Implicit Memory",
  "Implicit Prejudice",
  "Implicit Psychology",
  "Implicitly",
  "Implicitness Studies",
  "Implied Consent Law",
  "Implied Consent Psychology",
  "Implied Covenant",
  "Implied Metaphor",
  "Implied Meaning",
  "Implied Reader",
  "Implied Warranty",
  "Impliedly",
  "Implier Studies",
  "Implode Studies",
  "Implosion Studies",
  "Implosive Consonants",
  "Implosive Sounds",
  "Implore Studies",
  "Imploringly",
  "Implossible Studies",
  "Implosure Studies",
  "Imply Studies",
  "Implying Studies",
  "Impod Studies",
  "Impolder Studies",
  "Impolders",
  "Impolice Studies",
  "Impolitic Studies",
  "Impolitically",
  "Impolitical Studies",
  "Impolitically",
  "Impoliteness Studies",
  "Impolka Studies",
  "Impolled Studies",
  "Impolling",
  "Impolmade Studies",
  "Impolmen Studies",
  "Impolo Studies",
  "Impolred Studies",
  "Impolst Studies",
  "Impolte Studies",
  "Impoltroon Studies",
  "Impoluce Studies",
  "Impomel Studies",
  "Impolo Studies",
  "Impolon Studies",
  "Impolous Studies",
  "Impolred Studies",
  "Impolson Studies",
  "Impolster Studies",
  "Impolted Studies",
  "Impolure Studies",
  "Impolve Studies",
  "Impoly Studies",
  "Impompom Studies",
  "Impon Studies",
  "Imponderable Studies",
  "Imponderables",
  "Imponderably",
  "Imponderate Studies",
  "Imponderosa Studies",
  "Imponderous Studies",
  "Impondre Studies",
  "Imponence Studies",
  "Imponent Studies",
  "Imponent Verb",
  "Impone Studies",
  "Imponee Studies",
  "Imponement Studies",
  "Imponer Studies",
  "Imponerate Studies",
  "Imponent Studies",
  "Imponerture Studies",
  "Impones Studies",
  "Imponey Studies",
  "Impongeable Studies",
  "Imponge Studies",
  "Imponged Studies",
  "Imponges Studies",
  "Imponging Studies",
  "Imponi Studies",
  "Imponible Studies",
  "Imponis Studies",
  "Impont Studies",
  "Imponts Studies",
  "Impony Studies",
  "Imponyme Studies",
  "Impoo Studies",
  "Impoolable Studies",
  "Impoole Studies",
  "Impoond Studies",
  "Impoor Studies",
  "Impoort Studies",
  "Impopion Studies",
  "Impopular Studies",
  "Impopularly",
  "Impopularness",
  "Impopularity",
  "Impopulate Studies",
  "Impopule Studies",
  "Impore Studies",
  "Imporium Studies",
  "Imporosity Studies",
  "Imporous Studies",
  "Imporque Studies",
  "Imporrate Studies",
  "Imporrea Studies",
  "Imporrect Studies",
  "Imporred Studies",
  "Imporred Studies",
  "Imporro Studies",
  "Imporrosity Studies",
  "Imporrosity Studies",
  "Imporrosive Studies",
  "Impors Studies",
  "Importable Studies",
  "Importance Psychology",
  "Importance Studies",
  "Importanced Studies",
  "Importancy",
  "Important Events",
  "Important Law",
  "Important Politics",
  "Important Psychology",
  "Important Studies",
  "Importantly",
  "Importancy",
  "Importanite Studies",
  "Importantless Studies",
  "Importantsly Studies",
  "Importantuous Studies",
  "Importantute Studies",
  "Importantutely Studies",
  "Importantuous Studies",
  "Importantute Studies",
  "Importer Studies",
  "Importer Economics",
  "Importer Law",
  "Importers & Exporters",
  "Importery Studies",
  "Importe Studies",
  "Imported Materials",
  "Imported Studies",
  "Imported Technology",
  "Importedly",
  "Importedness Studies",
  "Importer Studies",
  "Importers Law",
  "Importers Psychology",
  "Importers Sociology",
  "Importery",
  "Importess Studies",
  "Importet Studies",
  "Importeth Studies",
  "Importful Studies",
  "Importfully",
  "Importfulness Studies",
  "Importial Studies",
  "Importially Studies",
  "Importible Studies",
  "Importible Studies",
  "Importical Studies",
  "Importically Studies",
  "Importide Studies",
  "Importidy Studies",
  "Importience Studies",
  "Importiency Studies",
  "Importiency Studies",
  "Importient Studies",
  "Importiently Studies",
  "Importies Studies",
  "Importificate Studies",
  "Importificate Studies",
  "Importificated Studies",
  "Importificates Studies",
  "Importificating Studies",
  "Importification Studies",
  "Importificator Studies",
  "Importified Studies",
  "Importifiel Studies",
  "Importifiel Studies",
  "Importifier Studies",
  "Importifiers Studies",
  "Importifies Studies",
  "Importifil Studies",
  "Importifilly Studies",
  "Importifilness Studies",
  "Importifully Studies",
  "Importifully Studies",
  "Importifung Studies",
  "Importifusive Studies",
  "Importig Studies",
  "Importige Studies",
  "Importigent Studies",
  "Importigently Studies",
  "Importigible Studies",
  "Importigently Studies",
  "Importign Studies",
  "Importigness Studies",
  "Importihes Studies",
  "Importihunt Studies",
  "Importil Studies",
  "Importile Studies",
  "Importileient Studies",
  "Importilea Studies",
  "Importilely Studies",
  "Importileness Studies",
  "Importilien Studies",
  "Importilty Studies",
  "Importim Studies",
  "Importime Studies",
  "Importimely Studies",
  "Importimense Studies",
  "Importimense Studies",
  "Importimentary Studies",
  "Importin Studies",
  "Importina Studies",
  "Importinable Studies",
  "Importinae Studies",
  "Importinae Studies",
  "Importinal Studies",
  "Importinale Studies",
  "Importinalely Studies",
  "Importinalness Studies",
  "Importinable Studies",
  "Importinacion Studies",
  "Importinanc Studies",
  "Importinance Studies",
  "Importinance Studies",
  "Importinanced Studies",
  "Importinances Studies",
  "Importinancia Studies",
  "Importinancia Studies",
  "Importinancy Studies",
  "Importinancy Studies",
  "Importinand Studies",
  "Importinaned Studies",
  "Importinaning Studies",
  "Importinaningly Studies",
  "Importinans Studies",
  "Importinansly Studies",
  "Importinant Studies",
  "Importinante Studies",
  "Importinantly Studies",
  "Importinanu Studies",
  "Importinany Studies",
  "Importinape Studies",
  "Importinarately Studies",
  "Importinare Studies",
  "Importinare Studies",
  "Importinarely Studies",
  "Importinarely Studies",
  "Importinarement Studies",
  "Importinareness Studies",
  "Importinaretic Studies",
  "Importinaretical Studies",
  "Importinaretically Studies",
  "Importinaretics Studies",
  "Importinarified Studies",
  "Importinarified Studies",
  "Importinarifier Studies",
  "Importinarifiers Studies",
  "Importinarifies Studies",
  "Importinarify Studies",
  "Importinarifying Studies",
  "Importinarifully Studies",
  "Importinarifully Studies",
  "Importinarifulness Studies",
  "Importinarin Studies",
  "Importinarina Studies",
  "Importinarian Studies",
  "Importinarian Studies",
  "Importinarianism Studies",
  "Importinarianism Studies",
  "Importinarians Studies",
  "Importinarians Studies",
  "Importinarie Studies",
  "Importinarie Studies",
  "Importinariede Studies",
  "Importinarieded Studies",
  "Importinariedes Studies",
  "Importinarieding Studies",
  "Importinariedingly Studies",
  "Importinariedes Studies",
  "Importinariedized Studies",
  "Importinariedizes Studies",
  "Importinariedizing Studies",
  "Importinariel Studies",
  "Importinariel Studies",
  "Importinarieled Studies",
  "Importinarieledly Studies",
  "Importinarieledness Studies",
  "Importinarieledly Studies",
  "Importinarielle Studies",
  "Importinarielle Studies",
  "Importinarielless Studies",
  "Importinariellessly Studies",
  "Importinariellessness Studies",
  "Importinarielness Studies",
  "Importinary Studies",
  "Importinarie Studies",
  "Importinaries Studies",
  "Importinaries Studies",
  "Importinariess Studies",
  "Importinariety Studies",
  "Importinarified Studies",
  "Importinarified Studies",
  "Importinarifier Studies",
  "Importinarifiers Studies",
  "Importinarifies Studies",
  "Importinarify Studies",
  "Importinarifying Studies",
  "Importinariful Studies",
  "Importinarifull Studies",
  "Importinarifullty Studies",
  "Importinarifuly Studies",
  "Importinarifuly Studies",
  "Importinarif Studies",
  "Importinarily Studies",
  "Importinarily Studies",
  "Importinarilyness Studies",
  "Importinarilness Studies",
  "Importinariness Studies",
  "Importinaries Studies",
  "Importinariety Studies",
  "Importinarify Studies",
  "Importinarified Studies",
  "Importinarified Studies",
  "Importinarifier Studies",
  "Importinarifiers Studies",
  "Importinarifies Studies",
  "Importinarify Studies",
  "Importinarifying Studies",
  "Importinariful Studies",
  "Importinarifull Studies",
  "Importinarifullty Studies",
  "Importinarifuly Studies",
  "Importinarifuly Studies",
  "Importinariful Studies",
  "Importinariful Studies",
  "Importinariffiness Studies",
  "Importinarifingly Studies",
  "Importinariful Studies",
  "Importinarifulne Studies",
  "Importinarifullnes Studies",
  "Importinarifullness Studies",
  "Importinarfully Studies",
  "Importinarfully Studies",
  "Importinarfully Studies",
  "Importinarfulness Studies",
  "Importinarfulness Studies",
  "Importinarian Studies",
  "Importinarians Studies",
  "Importinarism Studies",
  "Importinaristique Studies",
  "Importinarit Studies",
  "Importinarit Studies",
  "Importinarita Studies",
  "Importinaritair Studies",
  "Importinaritarian Studies",
  "Importinaritarianism Studies",
  "Importinaritarians Studies",
  "Importinarite Studies",
  "Importinarite Studies",
  "Importinaritea Studies",
  "Importinariteal Studies",
  "Importinariteally Studies",
  "Importinaritean Studies",
  "Importinaritely Studies",
  "Importinaritely Studies",
  "Importinaritely Studies",
  "Importinariteness Studies",
  "Importinariteness Studies",
  "Importinariteness Studies",
  "Importinariter Studies",
  "Importinariteress Studies",
  "Importinariteria Studies",
  "Importinariterly Studies",
  "Importinariterlyness Studies",
  "Importinariterly Studies",
  "Importinariterlyness Studies",
  "Importinariterly Studies",
  "Importinariterlyness Studies",
  "Importinariternal Studies",
  "Importinariternic Studies",
  "Importinariterny Studies",
  "Importinariternity Studies",
  "Importinariterny Studies",
  "Importinariterny Studies",
  "Importinariterol Studies",
  "Importinariterologist Studies",
  "Importinariterologists Studies",
  "Importinariterous Studies",
  "Importinariterously Studies",
  "Importinariterousness Studies",
  "Importinariterously Studies",
  "Importinariterousness Studies",
  "Importinariterously Studies",
  "Importinariterousness Studies",
  "Importinariterously Studies",
  "Importinariterousness Studies",
  "Importinariterously Studies",
  "Importinariterousness Studies",
  "Importinariterously Studies",
  "Importinariterousness Studies",
  "Importinariterously Studies",
  "Importinariterousness Studies",
  "Importinariterously Studies",
  "Importinariterousness Studies",
  "Importinariter Studies",
  "Importinariterty Studies",
  "Importinariterus Studies",
  "Importinaritess Studies",
  "Importinaritese Studies",
  "Importinaritet Studies",
  "Importinaritete Studies",
  "Importinaritetely Studies",
  "Importinaritetal Studies",
  "Importinaritetelly Studies",
  "Importinariteten Studies",
  "Importinariteteness Studies",
  "Importinariteter Studies",
  "Importinaritetes Studies",
  "Importinariteth Studies",
  "Importinaritethly Studies",
  "Importinaritetly Studies",
  "Importinaritetly Studies",
  "Importinaritetly Studies",
  "Importinaritetness Studies",
  "Importinaritetness Studies",
  "Importinaritetness Studies",
  "Importinarite Studies",
  "Importinariteus Studies",
  "Importinariteut Studies",
  "Importinaritetually Studies",
  "Importinariteut Studies",
  "Importinaritevy Studies",
  "Importinaritey Studies",
  "Importinaritez Studies",
  "Importinariti Studies",
  "Importinaritia Studies",
  "Importinaritial Studies",
  "Importinaritially Studies",
  "Importinaritian Studies",
  "Importinaritianity Studies",
  "Importinaritians Studies",
  "Importinaritians Studies",
  "Importinaritibel Studies",
  "Importinaritible Studies",
  "Importinaritible Studies",
  "Importinaritibley Studies",
  "Importinaritic Studies",
  "Importinaritical Studies",
  "Importinaritically Studies",
  "Importinaritic Studies",
  "Importinaritical Studies",
  "Importinaritically Studies",
  "Importinariticism Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinaricide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinaricitice Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
  "Importinariticide Studies",
];

export const READER_CATEGORIES = [
  "Fiction",
  "Mystery & Thriller",
  "Science Fiction",
  "Fantasy",
  "Romance",
  "Adventure",
  "Historical Fiction",
  "Horror",
  "Young Adult",
  "Children's Books",
  "Self-Help",
  "Wellness & Mind",
  "Fitness & Health",
  "Memoir & Biography",
  "History",
  "Science",
  "Business & Economics",
  "Technology",
  "Psychology",
  "Art & Design",
  "Cooking",
  "Travel",
  "Poetry",
  "Drama / Plays",
  "Comics & Graphic Novels",
  "Reference Books",
  "Educational Books",
  "Study Guides",
  "Other",
];

/**
 * Get categories for a specific book type
 */
export const getCategoriesByBookType = (
  bookType: "school" | "university" | "reader"
): string[] => {
  switch (bookType) {
    case "school":
      return SCHOOL_CATEGORIES.sort((a, b) => a.localeCompare(b));
    case "university":
      return UNIVERSITY_CATEGORIES.sort((a, b) => a.localeCompare(b));
    case "reader":
      return READER_CATEGORIES.sort((a, b) => a.localeCompare(b));
    default:
      return READER_CATEGORIES.sort((a, b) => a.localeCompare(b));
  }
};
